server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: community-area
          uri: http://localhost:8083
          predicates:
            - Path=/api/area/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/(?<path>.*)
                replacement: /$\{path}
        - id: community-user
          uri: http://localhost:8084
          predicates:
            - Path=/api/user/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/(?<path>.*)
                replacement: /$\{path}
        - id: community-shop
          uri: http://localhost:8081
          predicates:
            - Path=/api/shop/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/(?<path>.*)
                replacement: /$\{path}
            - name: LogExecution
              args:
                simpleUid: true
                inSeconds: true
#            - Logging= true, true
#            - RewritePath=/api/(?<path>.*), /$\{path} -> 위와 같은 내용

logging:
  level:
    dev.yoon.gateway.filter: trace