# multi document yml : 하나의yml파일 안에 여러 개의 설정 파일을 적용
spring:
  profiles:
    active: test
# java -jar spring-boot.jar --trace
#    root: debug
#    패키지별로 레벨 설정 다르게 할 수 있다
#    dev.yoon: info



# 스프링 부트가 사용하는 설정이 아닌 따로 애플리케이션을 진행하기 위해 추가하는 설정
custom:
  property:
    single: custom-property
    comlist: comma,sparated,list,to,value
    ncp:
      id: api-id
      key: api-key
      url: https://ncp.com/

#---
## 현재 profile이 test일 경우 실행하는 문서
#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/demo_jpa_schema
#    username: demo_jpa
#    password: dudwlsdl12
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: false
#    properties:
#      hibernata:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#---
## 현재 profile이 test일 경우 실행하는 문서
#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  jpa:
##    hibernate : 테이블을 만들고 활용하는 framework
#    hibernate:
##      ddl-auto : 테이블을 생성하고 제거하는 과정을 자동으로하는 옵션
##      => 프로그램 실행시 테이블을 자동으로 생성했다가 프로그램 종료시 자동으로 제거
#      ddl-auto: create
##      테이블에 데이터를 남기기 위해서
##      ddl-auto: update
##      ddl-auto: none
##      실제로 불리는 sql문을 보여줄지 선택하는 옵션
#    show-sql: true
#    properties:
#      hibernata:
#        dialect: org.hibernate.dialect.H2Dialect
#---
#spring:
#  config:
#    activate:
#      on-profile: docker
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.17.0.1:3306/demo_jpa_schema
#    username: demo_jpa
#    password: dudwlsdl12
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: false
#    properties:
#      hibernata:
#        dialect: org.hibernate.dialect.MySQL8Dialect
