spring:
  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://springboot-db.cvqrxyomkoch.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: admin
    password: dudwlsdl12

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#      show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
