spring:
  application:
    name: config-client
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: refresh
  endpoint:
    refresh:
      enabled: true
